import 'C:/MDR/cypress/support/Function.js'
describe('Patient details', () => {
    
    let text = 'AwhilebackIneededtocounttheamountoflettersthatapieceoftextinanemailtemplatehadondhjhjkdhjhjhjhjdtyutl'
    let  NAT_ID = Math.random().toString(36).toUpperCase().slice(4,10);
    let  VEM_ID = Math.random().toString(36).toUpperCase().slice(4,12);
    let  MRN_ID = Math.random().toString(36).toUpperCase().slice(3,11);
    let text_1 = 'World Health Organization P.O. Box 1771, South Pacific Complex Private Bag 90-09 Port Vila, Vanuatu..'
    let text_2 = 'World Health Organization Ministry of Iatika Complex Cornwall Street PO Box 177 Port Vila, Vanuatu at'
    let  firstname = Math.random().toString(36).slice(2,16);
 
    beforeEach(() => {
      cy.visit('/')
      cy.Login_web('function calling')
    })
    
    it('Add a new patient', () => {
        
    //Step 1    
        cy.get('.mat-list-item-content').eq(1).click().click()
        cy.intercept('GET', 'https://mdr.test.thelattice.org/fhir/List?_include=List:subject&_sort=-_lastUpdated&_count=25&_total=accurate').as('list')
        cy.wait('@list')
        cy.get('.mat-button').eq(1).click()
        cy.get('.card-header').should('contain.text','Register patient').wait(1000)
        cy.get('.mat-step-text-label').eq(0).then(($valueString)=>{
            expect($valueString).to.have.text('Identification')
           })
        cy.get('.mat-step-header').eq(0).should('have.attr','aria-selected','true')
        cy.get('.card-header').find('.mat-icon').click()
        cy.get('body').click('top')
        cy.get('body').find('.mat-dialog-container').should('exist')
        cy.contains('NO, GO BACK').click()
        cy.get('body').find('.mat-dialog-container').should('not.exist')
        cy.get('.card-header').find('.mat-icon').click()
        cy.contains('YES, DISCARD').click()
        cy.get('.mat-headline').should('have.text','My patients')
        cy.get('.mat-button').eq(1).click()
        cy.get('input[formcontrolname="nationalId"]').type('123NationNational12')
        cy.get('input[formcontrolname="nationalId"]').should('have.value','123NationNation')
        cy.contains(' cancel ').click()
        cy.get('input[formcontrolname="nationalId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled').click()
        cy.get('.mat-step-text-label').eq(1).then(($valueString)=>{
            expect($valueString).to.have.text('Personal Details')
           })
        cy.contains('BACK').click()
        cy.get('input[formcontrolname="nationalId"]').type(NAT_ID)
        cy.contains('NEXT').should('be.disabled')
        cy.contains('VERIFY').click()
        cy.get('.ng-submitted > :nth-child(3) > .mat-subheading-1').should('have.text',' Unverified ')
        cy.get('input[formcontrolname="vemisId"]').type('VEMISID15CHARACTER')
        cy.get('input[formcontrolname="vemisId"]').should('have.value','VEMISID15CHARAC')
        cy.get('.mat-form-field').eq(2).find('.mat-icon').click()
        cy.get('input[formcontrolname="vemisId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled')
        cy.get('input[formcontrolname="vemisId"]').type(VEM_ID)
        cy.get('input[formcontrolname="mrnId"]').type('MRNID15CHARACTER')
        cy.get('input[formcontrolname="mrnId"]').should('have.value','MRNID15CHARACTE')
        cy.get('.mat-form-field').eq(3).find('.mat-icon').click()
        cy.get('input[formcontrolname="mrnId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled')
        cy.get('input[formcontrolname="mrnId"]').type(MRN_ID)
        cy.contains('NEXT').should('be.enabled').click()
        
    //Step 2
       cy.get('.mat-step-header').eq(1).should('have.attr','aria-selected','true')
        cy.get('.mat-step-text-label').eq(1).then(($valueString)=>{
            expect($valueString).to.have.text('Personal Details')
           })
        let text = 'AwhilebackIneededtocounttheamountoflettersthatapieceoftextinanemailtemplatehadondhjhjkdhjhjhjhjdtyutl'
        cy.get('input[formcontrolname="firstName"]').click()
        cy.get('body').click('bottom')
        cy.get('.error-hint').should('exist').and('have.text','Please enter first name ')
        cy.get('input[formcontrolname="firstName"]').type('Re')
        cy.get('.error-hint').should('exist').and('have.text','Please enter at least 3 characters')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(text)
        cy.get('input[formcontrolname="firstName"]').should('have.value','AwhilebackIneededtocounttheamountoflettersthatapieceoftextinanemailtemplatehadondhjhjkdhjhjhjhjdtyut')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(firstname)
        cy.get('input[formcontrolname="middleName"]').click()
        cy.get('body').click()
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="lastName"]').click()
        cy.get('body').click()
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('.mat-chip').eq(0).should('have.attr','aria-selected','true').and('have.text',' Date of Birth ')
        cy.get('input[formcontrolname="dobSelect"]').should('have.attr', 'data-placeholder','DD/MM/YYYY').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('exist').and('have.text',' Please select your DOB ')
        cy.get('.mat-chip').eq(1).click()
        cy.get('.mat-chip').eq(1).should('have.attr','aria-selected','true').and('have.text',' Age ')
        cy.get('input[formcontrolname="years"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('have.text',' Please enter Years ')
        cy.get('.mat-stepper-next').eq(1).should('be.disabled')
        cy.get('input[formcontrolname="years"]').type('111')
        cy.get('.error-hint').should('have.text',' Range 0 to 99 ')
        let age = String(Math.random()).substring(1,4)
        cy.get('input[formcontrolname="years"]').type('{selectall}{backspace}').type(age)
        cy.get('input[formcontrolname="month"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="month"]').type('13')
        cy.get('.error-hint').should('have.text',' Range 0 to 12 ')
        cy.get('input[formcontrolname="month"]').type('{selectall}{backspace}').type('11')
        cy.get('input[formcontrolname="days"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="days"]').type('32')
        cy.get('.error-hint').should('have.text',' Range 0 to 31 ')
        cy.get('input[formcontrolname="days"]').type('{selectall}{backspace}').type('31')
        cy.get('.mat-chip-list-wrapper').eq(1).should('contains.text',' Male  Female  Other ')
        cy.get('.mat-chip').eq(2).click()
        cy.get('.mat-chip').eq(2).should('have.attr','aria-selected','true').and('have.text',' Male ')
        cy.contains('BACK').click()
        cy.get('.mat-step-text-label').eq(0).should('have.text','Identification')
        cy.contains('NEXT').click()
        cy.get('.mat-stepper-next').eq(1).should('contain.text','NEXT').click()
        cy.get('.mat-step-text-label').eq(2).should('have.text',' Contact details ')
  //Step 3
        var mobile_n = String(Math.random()).substring(1,12)
        cy.get('input[formcontrolname="phoneNumber"]').type('1111')
        cy.get('.error-hint').should('contain.text',' Enter a valid phone number ')
        cy.get('input[formcontrolname="phoneNumber"]').type('{selectall}{backspace}').type(mobile_n)
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('1111')
        cy.get('.error-hint').should('contain.text',' Enter a valid phone number ')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('{selectall}{backspace}').type(mobile_n)
        cy.get('.error-hint').should('contain.text',' Enter a different phone number ')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('{selectall}{backspace}')
        cy.get('.mat-select-value').eq(3).click()
        cy.get('body').find('.mat-option').should('not.exist')
        cy.get('.mat-select-value').eq(2).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('body').click('bottom')
        cy.get('body').find('.error-hint').should('exist').and('contain.text',' Please select a Province ')
        let province = Math.floor(Math.random() * 6);
        cy.get('.mat-select-value').eq(2).click()
        cy.get('.mat-option').eq(province).click().wait(500)
        cy.get('.mat-select-value').eq(3).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('body').click('bottom')
        cy.get('body').find('.error-hint').should('exist').and('contain.text',' Please select an Island ')
        cy.get('.mat-select-value').eq(4).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('.mat-option').eq(0).click().wait(500)
        cy.get('.mat-select-value').eq(3).click()
        cy.get('.mat-option').eq(1).click().wait(500)
        cy.get('.mat-select-value').eq(4).click()
        cy.get('body').click('bottom')
        cy.get('body').find('.error-hint').should('exist').and('contain.text',' Please select an Area Council ')
        cy.get('.mat-select-value').eq(4).click()
        cy.get('.mat-option').eq(0).click()
        cy.get('input[formcontrolname="village"]').type(text_1)
        cy.get('input[formcontrolname="village"]').should('have.value','World Health Organization P.O. Box 1771, South Pacific Complex Private Bag 90-09 Port Vila, Vanuatu.')
        cy.get('input[formcontrolname="address1"]').type(text_2)
        cy.get('input[formcontrolname="address1"]').should('have.value','World Health Organization Ministry of Iatika Complex Cornwall Street PO Box 177 Port Vila, Vanuatu a')
        cy.get('input[formcontrolname="notes"]').type(text_1)
        cy.get('input[formcontrolname="notes"]').should('have.value','World Health Organization P.O. Box 1771, South Pacific Complex Private Bag 90-09 Port Vila, Vanuatu.').wait(600)
        cy.get('.mat-stepper-previous').eq(1).click()
        cy.get('.mat-step-text-label').eq(1).should('contains.text','Personal Details') 
        cy.get('.mat-stepper-next').eq(1).click()     
        cy.get('.mat-stepper-next').eq(2).click()
    //Step 4
        cy.get('.mat-step-text-label').eq(3).should('contains.text',' Education & Work ') 
        cy.contains('PREVIEW').should('be.enabled')  
        let edu = Math.floor(Math.random() * 5);
        cy.get('.mat-radio-group').eq(0).find('.mat-radio-label').eq(edu).click()
        cy.get('.mat-radio-group').eq(1).find('.mat-radio-label').eq(0).click()
        cy.get('.mat-horizontal-content-container').find('.mat-radio-group').should('have.length', 2)
        cy.get('.mat-radio-group').eq(1).find('.mat-radio-label').eq(1).click()
        cy.get('.mat-horizontal-content-container').find('.mat-radio-group').should('have.length', 3)
        cy.contains('PREVIEW').should('be.enabled').click()
    //Step 5
        cy.get('.mat-step-text-label').eq(4).should('have.text',' Preview ')
        cy.get('.edit-button').eq(3).click().wait(600)
        cy.get('.mat-step-text-label').eq(3).should('contains.text',' Education & Work ')
        cy.contains('PREVIEW').click()
        //cy.contains('SAVE').should('be.enabled').click()
        //cy.get('.mat-simple-snackbar').should('have.text', 'Patient Successfully Created')
        //cy.get('.mat-headline').should('have.text','My patients')
    })  
    
    it.only('Edit existing patient details', () => {
    //Patient profile
        cy.get('.mat-list-item-content').eq(1).click().click()
        cy.intercept('GET', 'https://mdr.test.thelattice.org/fhir/List?_include=List:subject&_sort=-_lastUpdated&_count=25&_total=accurate').as('list')
        cy.wait('@list')
        cy.get('.mat-input-element').type('Lkjarbht').wait(600) //Enter patient name
        cy.get('.mat-row > .cdk-column-patientsName').click()
        cy.contains('VIEW DETAILS').click()
        cy.get('.mat-display-3').should('have.text','Patient profile')
        cy.get('.mat-horizontal-stepper-header-container').should('have.text','1Identification2Personal Details3 Contact details 4 Education & Work 5 Preview ')
        cy.get('.mat-horizontal-content-container').find('.edit-button').should('exist')
        cy.get('.card-header').find('.mat-icon').click()
        cy.get('.card-header').find('.mat-button-wrapper').should('contains.text','VIEW DETAILS')        
        cy.contains('VIEW DETAILS').click()
    //Step 1
        cy.get('.edit-button').eq(0).click()
        cy.get('.card-header').should('contain.text','Edit patient profile').wait(1000)
        cy.get('.mat-step-text-label').eq(0).should('have.text','Identification')
        cy.get('.mat-step-header').eq(0).should('have.attr','aria-selected','true')
        cy.get('.card-header').should('contain.text','Edit patient profile')
        cy.get('input[formcontrolname="nationalId"]').invoke('val').then(($val)=>{
        if($val === ''){
            cy.get('input[formcontrolname="nationalId"]').should('be.empty') 
        }else{
            cy.get('input[formcontrolname="nationalId"]').invoke('val').should('not.be.empty')
            cy.contains(' cancel ').click()
        }
        })
        cy.get('input[formcontrolname="nationalId"]').type('123NationNational12')
        cy.get('input[formcontrolname="nationalId"]').should('have.value','123NationNation')
        cy.contains(' cancel ').click()
        cy.get('input[formcontrolname="nationalId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled').click()
        cy.get('.mat-step-text-label').eq(1).should('have.text','Personal Details')
        cy.contains('BACK').click()
        cy.get('input[formcontrolname="nationalId"]').type(NAT_ID)
        cy.contains('NEXT').should('be.disabled')
        cy.contains('VERIFY').click()
        cy.get('.ng-submitted > :nth-child(3) > .mat-subheading-1').should('have.text',' Unverified ')
        cy.get('input[formcontrolname="vemisId"]').invoke('val').then(($val)=>{
            if($val === ''){
                cy.get('input[formcontrolname="vemisId"]').should('be.empty') 
            }else{
                cy.get('input[formcontrolname="vemisId"]').invoke('val').should('not.be.empty')
                cy.get('.mat-form-field').eq(2).find('.mat-icon').click()
            }
            })
        cy.get('input[formcontrolname="vemisId"]').type('VEMISID15CHARACTER')
        cy.get('input[formcontrolname="vemisId"]').should('have.value','VEMISID15CHARAC')
        cy.get('.mat-form-field').eq(2).find('.mat-icon').click()
        cy.get('input[formcontrolname="vemisId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled')
        cy.get('input[formcontrolname="vemisId"]').type(VEM_ID)
        cy.get('input[formcontrolname="mrnId"]').invoke('val').then(($val)=>{
            if($val === ''){
                cy.get('input[formcontrolname="mrnId"]').should('be.empty') 
            }else{
                cy.get('input[formcontrolname="mrnId"]').invoke('val').should('not.be.empty')
                cy.get('.mat-form-field').eq(3).find('.mat-icon').click()
            }
            })
        cy.get('input[formcontrolname="mrnId"]').type('MRNID15CHARACTER')
        cy.get('input[formcontrolname="mrnId"]').should('have.value','MRNID15CHARACTE')
        cy.get('.mat-form-field').eq(3).find('.mat-icon').click()
        cy.get('input[formcontrolname="mrnId"]').should('have.value','')
        cy.contains('NEXT').should('be.enabled')
        cy.get('input[formcontrolname="mrnId"]').type(MRN_ID)
        cy.contains('NEXT').should('be.enabled').click()

    //Step 2
        cy.get('.mat-list-item-content').eq(1).click()
        cy.intercept('GET', 'https://mdr.test.thelattice.org/fhir/List?_include=List:subject&_sort=-_lastUpdated&_count=25&_total=accurate').as('list')
        cy.wait('@list')
        cy.get('.mat-input-element').type('Lkjarbht').wait(600) //Enter patient name
        cy.get('.mat-row > .cdk-column-patientsName').click()
        cy.contains('VIEW DETAILS').click()
        cy.get('.edit-button').eq(1).click()
        cy.get('.mat-step-header').eq(1).should('have.attr','aria-selected','true')
        cy.get('.mat-step-text-label').eq(1).should('have.text','Personal Details')
        cy.get('.card-header').should('contain.text','Edit patient profile')
        cy.get('input[formcontrolname="firstName"]').invoke('val').then(($val)=>{
            if($val === ''){
                cy.get('input[formcontrolname="firstName"]').should('be.empty') 
            }else{
                cy.get('input[formcontrolname="firstName"]').invoke('val').should('not.be.empty')
                cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}')
            }
            })
        cy.get('input[formcontrolname="firstName"]').click()
        cy.get('body').click('bottom')
        cy.get('.error-hint').should('exist').and('have.text','Please enter first name ')
        cy.get('input[formcontrolname="firstName"]').type('Re')
        cy.get('.error-hint').should('exist').and('have.text','Please enter at least 3 characters')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(text)
        cy.get('input[formcontrolname="firstName"]').should('have.value','AwhilebackIneededtocounttheamountoflettersthatapieceoftextinanemailtemplatehadondhjhjkdhjhjhjhjdtyut')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(firstname)
        cy.get('input[formcontrolname="middleName"]').click()
        cy.get('body').click()
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="lastName"]').click()
        cy.get('body').click()
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('.mat-chip').eq(0).should('have.attr','aria-selected','true').and('have.text',' Date of Birth ')
        cy.get('input[formcontrolname="dobSelect"]').should('have.attr', 'data-placeholder','DD/MM/YYYY')
        cy.get('input[formcontrolname="dobSelect"]').invoke('val').then(($val)=>{
            if($val === ''){
                cy.get('input[formcontrolname="dobSelect"]').should('be.empty') 
            }else{
                cy.get('input[formcontrolname="dobSelect"]').invoke('val').should('not.be.empty')
            }
            })
        cy.get('.mat-chip').eq(1).click()
        cy.get('input[formcontrolname="years"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('have.text',' Please enter Years ')
        cy.get('.mat-stepper-next').eq(1).should('be.disabled')
        cy.get('input[formcontrolname="years"]').type('111')
        cy.get('.error-hint').should('have.text',' Range 0 to 99 ')
        let age = String(Math.random()).substring(1,4)
        cy.get('input[formcontrolname="years"]').type('{selectall}{backspace}').type(age)
        cy.get('input[formcontrolname="month"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="month"]').type('13')
        cy.get('.error-hint').should('have.text',' Range 0 to 12 ')
        cy.get('input[formcontrolname="month"]').type('{selectall}{backspace}').type('1')
        cy.get('input[formcontrolname="days"]').click()
        cy.get('body').click('top')
        cy.get('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="days"]').type('32')
        cy.get('.error-hint').should('have.text',' Range 0 to 31 ')
        cy.get('input[formcontrolname="days"]').type('{selectall}{backspace}').type('31')
        cy.get('.mat-chip-list-wrapper').eq(1).should('contains.text',' Male  Female  Other ')
        cy.get('.mat-chip').eq(2).click()
        cy.get('.mat-chip').eq(2).should('have.attr','aria-selected','true').and('have.text',' Male ')
        cy.contains('BACK').click()
        cy.get('.mat-step-text-label').eq(0).should('have.text','Identification')
        cy.contains('NEXT').click()
        cy.get('.mat-stepper-next').eq(1).should('contain.text','NEXT').click()
        cy.get('.mat-step-text-label').eq(2).should('have.text',' Contact details ')
   
    //Step 3
        cy.get('.mat-list-item-content').eq(1).click()
        cy.intercept('GET', 'https://mdr.test.thelattice.org/fhir/List?_include=List:subject&_sort=-_lastUpdated&_count=25&_total=accurate').as('list')
        cy.wait('@list')
        cy.get('.mat-input-element').type('Lkjarbht').wait(600) //Enter patient name
        cy.get('.mat-row > .cdk-column-patientsName').click()
        cy.contains('VIEW DETAILS').click()
        cy.get('.edit-button').eq(2).click()
        cy.get('.mat-step-header').eq(2).should('have.attr','aria-selected','true')
        cy.get('.card-header').should('contain.text','Edit patient profile')
        var mobile_n = String(Math.random()).substring(1,12)        
        cy.get('input[formcontrolname="phoneNumber"]').type('{selectall}{backspace}').type('1111')
        cy.get('.error-hint').should('contain.text',' Enter a valid phone number ')
        cy.get('input[formcontrolname="phoneNumber"]').type('{selectall}{backspace}').type(mobile_n)
        cy.get('body').find('.error-hint').should('not.exist')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('{selectall}{backspace}').type('1111')
        cy.get('.error-hint').should('contain.text',' Enter a valid phone number ')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('{selectall}{backspace}').type(mobile_n)
        cy.get('.error-hint').should('contain.text',' Enter a different phone number ')
        cy.get('input[formcontrolname="secPhoneNumber"]').type('{selectall}{backspace}')
        cy.get('.mat-select-value').eq(2).invoke('val').then(($val)=>{
            cy.log($val)
            if($val == null){
                cy.get('.mat-select-value').eq(2).should('be.empty') 
            }else{
                cy.get('.mat-select-value').eq(2).should('not.be.empty')
            }
            })
        cy.get('.mat-select-value').eq(2).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('body').click('bottom')
        let province = Math.floor(Math.random() * 6);
        cy.get('.mat-select-value').eq(2).click()
        cy.get('.mat-option').eq(province).click().wait(500)
        cy.get('.mat-select-value').eq(3).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('body').click('bottom')
        cy.get('body').find('.error-hint').should('exist').and('contain.text',' Please select an Island ')
        cy.get('.mat-select-value').eq(4).click()
        cy.get('body').find('.mat-option').should('exist')
        cy.get('.mat-option').eq(0).click().wait(500)
        cy.get('.mat-select-value').eq(3).click()
        cy.get('.mat-option').eq(1).click().wait(500)
        cy.get('.mat-select-value').eq(4).click()
        cy.get('body').click('bottom')
        cy.get('body').find('.error-hint').should('exist').and('contain.text',' Please select an Area Council ')
        cy.get('.mat-select-value').eq(4).click()
        cy.get('.mat-option').eq(0).click()
        cy.get('input[formcontrolname="village"]').type('{selectall}{backspace}').type(text_1)
        cy.get('input[formcontrolname="village"]').should('have.value','World Health Organization P.O. Box 1771, South Pacific Complex Private Bag 90-09 Port Vila, Vanuatu.')
        cy.get('input[formcontrolname="address1"]').type('{selectall}{backspace}').type(text_2)
        cy.get('input[formcontrolname="address1"]').should('have.value','World Health Organization Ministry of Iatika Complex Cornwall Street PO Box 177 Port Vila, Vanuatu a')
        cy.get('input[formcontrolname="notes"]').type('{selectall}{backspace}').type(text_1)
        cy.get('input[formcontrolname="notes"]').should('have.value','World Health Organization P.O. Box 1771, South Pacific Complex Private Bag 90-09 Port Vila, Vanuatu.').wait(600)
        cy.get('.mat-stepper-previous').eq(1).click()
        cy.get('.mat-step-text-label').eq(1).should('contains.text','Personal Details') 
        cy.get('.mat-stepper-next').eq(1).click()     
        cy.get('.mat-stepper-next').eq(2).click()

    //Step 4
        cy.get('.mat-step-text-label').eq(3).should('have.text',' Education & Work ')
        cy.contains('PREVIEW').should('be.enabled').click()
        cy.get('.mat-list-item-content').eq(1).click()
        cy.intercept('GET', 'https://mdr.test.thelattice.org/fhir/List?_include=List:subject&_sort=-_lastUpdated&_count=25&_total=accurate').as('list')
        cy.wait('@list')
        cy.get('.mat-input-element').type('Lkjarbht').wait(600) //Enter patient name
        cy.get('.mat-row > .cdk-column-patientsName').click()
        cy.contains('VIEW DETAILS').click()
        cy.get('.edit-button').eq(3).click()
        cy.get('.mat-step-header').eq(3).should('have.attr','aria-selected','true')
        cy.get('.card-header').should('contain.text','Edit patient profile')
        cy.get('.mat-step-text-label').eq(3).should('have.text',' Education & Work ')
        cy.contains('PREVIEW').should('be.enabled')
        let edu = Math.floor(Math.random() * 5);
        cy.get('.mat-radio-group').eq(0).find('.mat-radio-label').eq(edu).click()
        cy.get('.mat-radio-group').eq(1).find('.mat-radio-label').eq(0).click()
        cy.get('.mat-horizontal-content-container').find('.mat-radio-group').should('have.length', 2)
        cy.get('.mat-radio-group').eq(1).find('.mat-radio-label').eq(1).click()
        cy.get('.mat-horizontal-content-container').find('.mat-radio-group').should('have.length', 3)
        cy.get('.mat-radio-group').eq(2).find('.mat-radio-label').eq(2).click()
        cy.contains('PREVIEW').should('be.enabled').click()

    //Step 5
        cy.get('.mat-step-text-label').eq(4).should('have.text',' Preview ')
        cy.contains('SAVE').should('be.enabled').click()
        cy.get('.mat-simple-snackbar').should('have.text', 'Patient Successfully Updated')
        let edit = Math.floor(Math.random() * 4);
        cy.contains('VIEW DETAILS').click()
        cy.get('.edit-button').eq(edit).click()
        cy.get('.card-header').find('.mat-icon').click()
        cy.get('.mat-dialog-container').should('exist')
        cy.contains('YES, DISCARD').click()
        cy.get('.card-header').should('contain.text','Lkjarbht') // Patient name should exist on landing screen
    })
})