import 'C:/MDR/cypress/support/Function.js'
describe('Patient details', () => {

    beforeEach(() => {
        var text="";
        cy.visit('/')
        cy.Login_web_HealthcarePro('function calling')
        //cy.Login_web('function calling')
    })
    it('Patient list', () => {
        cy.get('.headerWrapper').should('contain.text','My patientsdownloadDOWNLOADperson_addADD PATIENT')
        cy.get('.mat-drawer-content > .mat-toolbar').find('.profile-card').should('exist')
        cy.get('.profile-card').click()
        cy.get('body').find('.mat-menu-content').should('exist')
        cy.get('.mat-menu-content').should('contain.text','Phone number+678' && 'CHANGE PASSWORDLOGOUT')
        cy.get('body').click('top')
        cy.get('body').find('.mat-menu-content').should('not.exist')
        cy.get('.profile-card').click()
        cy.get('.mat-menu-content').contains('CHANGE PASSWORD').click()
        cy.get('body').find('.mat-dialog-container').should('exist')
        cy.contains('CANCEL').click()
        cy.get('body').find('.mat-dialog-container').should('not.exist')
        cy.get('.profile-card').click()
        cy.get('.mat-menu-content').contains('LOGOUT').click()
        cy.get('.mat-dialog-container').contains('LOGOUT').click()
        cy.get('.mat-simple-snackbar').should('have.text', 'You have successfully logged out!')
    //Upto empty list view
        cy.Login_web_HealthcarePro('function calling')
        cy.contains('DOWNLOAD').click()
// This method is used to download file & check the downloaded file size to check wheather file is downloaded or not
        cy.readFile("C:/MDR/cypress/downloads/exported_data.csv")
        .should('exist')
        .then((fileContent) => {
            expect(fileContent.length).to.equal(3028)
        })
        cy.get('body').click('bottomLeft')
        cy.get('.mat-raised-button').eq(0).click()
        cy.get('.mat-display-3').should('contain.text', 'Register patient')
        cy.get('.mat-icon').eq(3).click()
        cy.get('mat-dialog-container').contains('YES, DISCARD').click()
        cy.get('.mat-headline').should('contain.text', 'My patients')
        cy.get('.mat-radio-input').eq(0).should('be.checked').and('have.attr', 'tabindex', '0')
        cy.get('.mat-input-element').type('Testing')
        cy.get('.mat-table').find('.mat-row').should('exist')
        cy.get('.mat-input-element').type('{selectall}{backspace}').wait(1000).type('1P6FTT')
        cy.get('.mat-display-4').should('contain.text', 'No results found')
        cy.get('.mat-table').find('.mat-row').should('not.exist')
        cy.get('.mat-radio-button').eq(1).click()
        cy.get('.mat-input-element').should('have.attr', 'data-placeholder','Type National ID here')
        cy.get('.mat-input-element').type('Mar').wait(700).type('i').wait(700).type('e')
        cy.get('.mat-table').find('.mat-row').should('exist')
        cy.get('.mat-radio-button').eq(0).click()
        cy.get('.mat-input-element').should('have.attr', 'data-placeholder','Type Patient name here')
        cy.get('.stocked-button').eq(1).click()
        cy.get('.mat-select-value').eq(0).click()
        let province = Math.floor(Math.random() * 6);
        cy.get('.mat-option').eq(province).click().wait(1000)
        cy.get('.mat-select-value').eq(1).click()
        let area = Math.floor(Math.random() * 8);
        cy.get('.mat-option').eq(area).click()
        cy.get('.stocked-button').eq(1).click().wait(1000)
        cy.get('.mat-row .cdk-column-patientsName').eq(1).click()
        cy.get('.card-header').find('.header-button ').should('have.text','VIEW DETAILS')
        cy.get('.mat-icon').eq(3).click()
        cy.get('.mat-raised-button').eq(1).should('contain.text', 'SHOW WG-SS RESULTS').click()
        cy.get('.mat-card').find('.mat-raised-button').eq(1).should('contain.text', 'HIDE WG-SS RESULTS')
        cy.get('.stocked-button').eq(1).click().wait(1000)
    })
})