import 'C:/MDR/cypress/support/Function.js'
describe('User details', () => {
  let  name = Math.random().toString(36).slice(1,16);  
  beforeEach(() => {
      cy.visit('/')
      cy.Login_web('function calling').wait(1000)
      cy.clearLocalStorage()
    })

    it('User list', () => {
      cy.get('.card-header').should('contains.text','Users ')
      cy.get('.profile-card ').click()
      cy.get('.mat-menu-content').should('be.exist')
      cy.get('body').click('bottom')
      cy.get('.mat-menu-content').should('not.exist')
      cy.get('.mat-header-row').should('contains.text','Full Name  Organization  Role  Mobile #  Status ') 
      cy.get('.select-filter').eq(0).should('contains.text','AllOrganizationAllRoleAllStatus')
      cy.get('.mat-form-field').eq(0).should('contain.text','All').click()
      cy.get('.mat-select-panel').should('exist')
      cy.get('body').click('bottom')
      cy.get('.mat-form-field').eq(1).should('contain.text','All').click()
      cy.get('.mat-select-panel').should('exist') 
      cy.get('body').click('bottom')
      cy.get('.mat-form-field').eq(1).click()
      cy.get('.mat-option').contains('Admin').click()
      cy.get('.mat-form-field').eq(2).should('contain.text','All').click()
      cy.get('.mat-select-panel').should('exist') 
      cy.get('body').click('bottom')
      cy.get('.mat-form-field').eq(2).click()
      cy.get('.mat-option').contains('Active').click()
      cy.get('.mat-form-field').eq(3).type('KR$NA')
      cy.get('.mat-elevation-z8').find('.no-content-text').should('exist').and('have.text',' No results found ')
      cy.contains(' RESET FILTERS').click()
    //Enter name that is existed in the list  
      cy.get('.mat-form-field').eq(3).type('Device')
      cy.get('.mat-table').find('.mat-row').should('exist')
      cy.get('.mat-form-field').eq(3).type('{selectall}{backspace}').type('Port Villa')
      cy.get('.mat-table').find('.mat-row').should('exist')
      cy.get('.mat-form-field').eq(3).type('{selectall}{backspace}').type('Admin')
      cy.get('.mat-table').find('.mat-row').should('exist')
      cy.get('.mat-form-field').eq(3).type('{selectall}{backspace}').type('333333')
      cy.get('.mat-table').find('.mat-row').should('exist')
      cy.get('.mat-form-field').eq(3).type('{selectall}{backspace}').type('Active')
      cy.get('.mat-table').find('.mat-row').should('exist')
      cy.get('.mat-form-field').eq(3).type('{selectall}{backspace}').type('KR$NA')
      cy.get('.mat-form-field-suffix').click()
      cy.get('.mat-form-field').eq(3).should('have.value', '');
      cy.contains(' RESET FILTERS').should('be.disabled')
      cy.get('.mat-form-field').eq(3).type('Device')
      cy.contains(' RESET FILTERS').should('be.enabled')
      cy.get('.mat-select-value').eq(3).should('have.text','25').click()
      cy.get('.mat-select-panel').should('exist')
    })
    it('Add a new user', () => {
        cy.get('.mat-raised-button').eq(0).click()
        cy.get('body').find('.mat-dialog-container').should('be.exist').and('contain.text',' Add User ')
        cy.get('.mat-display-3').should('have.text',' Add User ')
        cy.contains('CANCEL').click()
        cy.get('body').find('.mat-dialog-container').should('not.exist')
        cy.get('.card-header').should('contain.text','Users ')
        cy.get('.mat-raised-button').eq(0).click()
        cy.get('.mat-display-3').click()
        cy.get('body').click()
        cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Please enter at least 3 characters ')
        cy.get('input[formcontrolname="firstName"]').should('be.enabled').type('Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="firstName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type('Awhilebackneededtocountthenumberoflettersthagebhbds')
        cy.get('input[formcontrolname="firstName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(name)
        let  familyname = Math.random().toString(36).slice(1,16);  
        cy.get('input[formcontrolname="lastName"]').click().should('be.enabled')
        cy.get('.mat-display-3').click()
        cy.get('.mat-dialog-container').find('.error-hint').should('be.not.exist')
        cy.get('input[formcontrolname="lastName"]').should('be.enabled').type('Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="lastName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="lastName"]').type('{selectall}{backspace}').type('Awhilebackneededtocountthenumberoflettersthagebhbds')
        cy.get('input[formcontrolname="lastName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
        cy.get('input[formcontrolname="lastName"]').type('{selectall}{backspace}').type(familyname)
        cy.get('input[formcontrolname="mobileNumber"]').click().should('be.enabled')
        cy.get('.mat-display-3').click()
        cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Enter a valid mobile number ')
        cy.get('input[formcontrolname="mobileNumber"]').type('123')
        cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', 'Enter a valid mobile number ')
        cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type('98765432101')
        cy.get('input[formcontrolname="mobileNumber"]').should('have.value','9876543210')
        cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type('333333')
      //Selecting orgainization
        cy.get('.mat-select-value').eq(4).click()
        cy.get('body').find('.mat-select-panel').should('exist')
        cy.get('body').click('bottom')
        cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Please select an organization ')
        cy.get('.mat-select-value').eq(4).click()
        cy.get('.mat-option').eq(3).click()
      //Selecting Role
        cy.get('.mat-select-value').eq(5).click()
        cy.get('body').click().find('.mat-select-panel').should('exist')
        cy.get('body').click('bottom')
        cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Please select a role ')
        cy.get('.mat-select-value').eq(5).click()
        cy.get('.mat-option').eq(2).click()
        cy.get('.mat-dialog-container').find('.mat-slide-toggle-content').should('contain.text','User account is active')
        cy.get('.mat-dialog-container').find('.mat-slide-toggle-thumb').click()
        cy.get('.mat-dialog-container').find('.mat-slide-toggle-content').should('contain.text','User account is inactive')
        cy.get('body').click('topRight')
        cy.get('.mat-dialog-container').should('exist')
        cy.contains('SAVE').click()
        cy.get('.mat-simple-snackbar').should('have.text', 'Duplicate mobile number')
        var mobile_n = String(Math.random()).substring(1,11)
        cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type(mobile_n)
        cy.contains('SAVE').should('be.enabled')//.click()
        //cy.get('.mat-simple-snackbar').should('have.text', 'User added')
    })
    
    it('Edit existing user details', () => {
      cy.get('.mat-input-element').type('Krsna') //(name)
      cy.get('.cdk-column-edit > .mat-icon').click().wait(1000)
      cy.get('body').find('.mat-dialog-container').should('be.exist')
      cy.get('.mat-display-3').should('have.text',' Edit User ')
      cy.contains('CANCEL').click()
      cy.get('body').find('.mat-dialog-container').should('not.exist')
      cy.get('.card-header').should('contain.text','Users ')
      cy.get('.cdk-column-edit > .mat-icon').click().wait(1000)
      cy.get('input[formcontrolname="firstName"]').should('be.enabled').type('{selectall}{backspace}')
      cy.get('.mat-display-3').click()
      cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Please enter at least 3 characters ')
      cy.get('input[formcontrolname="firstName"]').should('be.enabled').type('Awhilebackneededtocountthenumberoflettersthagebhbd')
      cy.get('input[formcontrolname="firstName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
      cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type('Awhilebackneededtocountthenumberoflettersthagebhbds')
      cy.get('input[formcontrolname="firstName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')  
      cy.get('input[formcontrolname="firstName"]').type('{selectall}{backspace}').type(name)
      let  familyname = Math.random().toString(36).slice(1,16);  
      cy.get('input[formcontrolname="lastName"]').should('be.enabled').type('{selectall}{backspace}')
      cy.get('.mat-display-3').click()
      cy.get('.mat-dialog-container').find('.error-hint').should('be.not.exist')
      cy.get('input[formcontrolname="lastName"]').should('be.enabled').type('Awhilebackneededtocountthenumberoflettersthagebhbd')
      cy.get('input[formcontrolname="lastName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')
      cy.get('input[formcontrolname="lastName"]').type('{selectall}{backspace}').type('Awhilebackneededtocountthenumberoflettersthagebhbds')
      cy.get('input[formcontrolname="lastName"]').should('have.value','Awhilebackneededtocountthenumberoflettersthagebhbd')  
      cy.get('input[formcontrolname="lastName"]').type('{selectall}{backspace}').type(familyname)
      var mobile_n = String(Math.random()).substring(1,11)
      cy.get('input[formcontrolname="mobileNumber"]').should('be.enabled').type('{selectall}{backspace}')
      cy.get('.mat-display-3').click()
      cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', ' Enter a valid mobile number ')
      cy.contains('SAVE').should('be.disabled')
      cy.get('input[formcontrolname="mobileNumber"]').type('123')
      cy.get('.mat-dialog-container').find('.error-hint').should('be.exist').and('have.text', 'Enter a valid mobile number ')
      cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type('98765432101')
      cy.get('input[formcontrolname="mobileNumber"]').should('have.value','9876543210')
      cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type('333333')
      cy.contains('SAVE').click()
      cy.get('.mat-simple-snackbar').should('have.text', 'Duplicate mobile number') 
      cy.get('input[formcontrolname="mobileNumber"]').type('{selectall}{backspace}').type(mobile_n)
    //Selecting orgainization
      cy.get('.mat-select-value').eq(4).click()
      cy.get('body').find('.mat-select-panel').should('exist')
      cy.get('.mat-option').eq(1).click()
    //Selecting Role
      cy.get('.mat-select-value').eq(5).click()
      cy.get('body').find('.mat-select-panel').should('exist')  
      cy.get('.mat-option').eq(4).click().wait(1000)
      cy.get('body').click('topRight')
      cy.get('.mat-dialog-container').should('exist')  
      cy.contains('SAVE').should('be.enabled').click()
     cy.get('.mat-simple-snackbar').should('have.text', 'User updated')
  })  

  it.only('Edit existing user details', () => {
    cy.get('.mat-card-content').then(($details) => {
      if ($details.text().includes('Active')) {
        cy.contains('Active').click()
        cy.get('.mat-dialog-container').should('exist')
        cy.get('.mat-dialog-container').should('contain.text',' Are you sure you want to deactivate user account? ')
        cy.contains('NO, GO BACK').click().wait(1000)
        cy.get('.mat-dialog-container').should('not.exist')
        cy.contains('Active').click().click()
        cy.contains('YES, CHANGE').click()
        cy.get('.mat-simple-snackbar').should('have.text', 'User status updated')
        cy.contains('Inactive').click()
        cy.get('.mat-simple-snackbar').should('have.text', 'User status updated') 
        }
      else{
        cy.log('Currently,no user status is active.')
      }
    })
  })
})