import 'C:/MDR/cypress/support/Function.js'
describe('Login module', () => {
      const number = '9999999999'
      const pass = 'Pass@123'  
  beforeEach(() => {
      cy.clearLocalStorage()
      cy.visit('/')  
      
    })
  
    it('Login to the application', () => {
      cy.get('.mat-subheading-1').should('have.text',' Login with phone number ')
      cy.contains('VERIFY').should('be.disabled')
      cy.get('.mat-form-field-label').should('have.text','Mobile Number *')
      cy.get('.mat-form-field').should('be.visible').type('1212')
      cy.get('.mat-hint').should('have.text','Enter a valid mobile number ')
      cy.get('.mat-form-field').type('{selectall}{backspace}').type('djhdj')
      cy.get('.mat-form-field').type('78732222223').type('{selectall}{backspace}').type('12121')
      cy.contains('VERIFY').should('be.enabled')
      cy.get('.mat-icon').click()
      cy.get('.mat-form-field').invoke('val').then((value) => {
        if (value === '') {
          cy.log('The input field is empty')
        }
      })
      cy.get('.mat-form-field').type('9897682232')
      cy.reload()
      cy.get('.mat-form-field').type('78733')
      cy.contains('VERIFY').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Unauthorized user')
      cy.get('.mat-form-field').type('{selectall}{backspace}').type(number)
      cy.contains('VERIFY').should('be.visible').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'User verified')
      cy.get('.mat-subheading-1').should('have.text',' Enter the password ')
      cy.get('.mat-form-field').type('Himan8755@')
      cy.contains('VERIFY').should('be.visible').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Incorrect password')
      cy.get('.mat-form-field').type('{selectall}{backspace}').type(pass)
      cy.contains('VERIFY').should('be.visible').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Logged in successfully')
    })
    
    it('Change Password', () => {
      cy.Login_web('function calling')
      cy.get('.profile-card').click()
      cy.get('.mat-menu-content').should('be.exist')
      cy.contains('CHANGE PASSWORD').click()
      cy.get('.mat-dialog-container').should('be.exist')
      cy.get('.mat-subheading-1').eq(1).should('have.text',' Change password ')
      cy.get('body').click('bottom')
      cy.get('.mat-dialog-container').should('be.exist')
      cy.get('input[formcontrolname="currentPassword"]').type("Himan8755@")
      cy.get('input[formcontrolname="newPassword"]').type(pass)
      cy.get('input[formcontrolname="confirmPassword"]').type(pass)
      cy.contains('SAVE').should('be.enabled').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Invalid old password')
      cy.get('input[formcontrolname="currentPassword"]').type('{selectall}{backspace}').type(pass)
      cy.contains('SAVE').should('be.enabled').click().wait(2000)
      cy.get('.mat-simple-snackbar').should('have.text', 'Password changed.')
      cy.get('.mat-form-field').type(number)
      cy.contains('VERIFY').click()
      cy.get('.mat-form-field').type(pass)
      cy.contains('VERIFY').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Logged in successfully')
    }) 
    
    it.only('Logout', () => {
      cy.Login_web('function calling')
      cy.get('.profile-card').click()
      cy.get('.mat-menu-content').should('be.exist')
      cy.contains('LOGOUT').click()
      cy.get('.mat-dialog-container').should('be.exist').and('contain.text', ' Are you sure you want to logout? ')
      cy.get('.mat-dialog-container').find('.mat-button-wrapper').eq(0).click()
      cy.get('.mat-dialog-container').should('not.exist')
      cy.get('.profile-card').click()
      cy.contains('LOGOUT').click()
      cy.get('.mat-dialog-container').find('.mat-button-wrapper').eq(1).click()
      cy.get('.mat-card').should('contain.text',' Login with phone number ')
      cy.get('.mat-form-field').type('98976822')
      cy.contains('VERIFY').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Unauthorized user')
      cy.get('.mat-form-field').type('{selectall}{backspace}').type(number)
      cy.contains('VERIFY').should('be.visible').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'User verified')
    
    })
    
    it('Forgot password', () => {
      cy.get('.mat-form-field').type(number)
      cy.contains('VERIFY').should('be.enabled').click()
      cy.contains('FORGOT PASSWORD').click().wait(1000)
      cy.get('.mat-subheading-1').eq(0).should('have.text',' Enter the OTP we sent to ')
      cy.get('.mat-simple-snackbar').should('have.text', 'User verified. OTP sent to your registered contact detail')
      cy.contains('BACK').click()
      cy.get('.mat-subheading-1').should('have.text',' Login with phone number ')
      cy.get('.mat-form-field').type(number)
      cy.contains('VERIFY').should('be.enabled').click()
      cy.contains('FORGOT PASSWORD').click().wait(1000)
      cy.get('input[id="ngx-otp-input-0"]').type('1')
      cy.get('input[id="ngx-otp-input-1"]').type('1')
      cy.get('input[id="ngx-otp-input-2"]').type('1')
      cy.get('input[id="ngx-otp-input-3"]').type('1')
      cy.get('input[id="ngx-otp-input-4"]').type('1')
      cy.get('input[id="ngx-otp-input-5"]').type('3')
      cy.contains('VERIFY').should('be.enabled').click()
      cy.get('.mat-simple-snackbar').should('have.text', 'Invalid OTP')
      cy.get('input[id="ngx-otp-input-5"]').type('{selectall}{backspace}').type('1')
      cy.contains('VERIFY').click()
      cy.get('.mat-subheading-1').should('have.text',' Create New Password ')
      cy.get('.mat-hint').eq(0).should('have.text','8-15 characters, with at least one number, special, uppercase, and lowercase characters ').and('have.css', 'color', 'rgb(128, 128, 128)')
      cy.get('.mat-card').should('contain.text',' Create New Password ')
      cy.get('input[formcontrolname="password"]').type(pass)
      cy.get('input[formcontrolname="confirmPassword"]').type("Pass")
      cy.get('.mat-hint').should('have.length','1')
      cy.contains('CANCEL').click()
      cy.get('.mat-subheading-1').should('have.text',' Login with phone number ')
      cy.get('.mat-form-field').type(number)
      cy.contains('VERIFY').click()
      cy.contains('FORGOT PASSWORD').click().wait(1000)
      cy.get('input[id="ngx-otp-input-0"]').type('1')
      cy.get('input[id="ngx-otp-input-1"]').type('1')
      cy.get('input[id="ngx-otp-input-2"]').type('1')
      cy.get('input[id="ngx-otp-input-3"]').type('1')
      cy.get('input[id="ngx-otp-input-4"]').type('1')
      cy.get('input[id="ngx-otp-input-5"]').type('1')
      cy.contains('VERIFY').should('be.enabled').click()
      cy.get('input[formcontrolname="password"]').type(pass)
      cy.get('input[formcontrolname="confirmPassword"]').type("Himan8755@")
      cy.get('.mat-hint').eq(1).should('contain.text','Password do not match ')
      cy.contains('SAVE').should('be.disabled')
      cy.get('input[formcontrolname="confirmPassword"]').type('{selectall}{backspace}').type(pass)
      cy.contains('SAVE').should('be.enabled').click()
      cy.get('.mat-simple-snackbar').should('be.exist').and('have.text', 'Password set.')
      cy.get('.mat-card').should('contain.text',' Login with phone number ')
    })
})